### ISSUE TITLE
Epson scan tif files don't work

### ISSUE THREAD

**Issue by Mkorho** [doug3236/scanner_refl_fix#2]
I am very interested to improve my scans, but for some reason "Epson scan" tif files are not read.
The test file in repository works just fine.

Target was printed on 10x15cm (4x6in) Premium Glossy Paper.

Program output:
C:\Argyll_V2.1.2\scanner_refl_fix>scanner_refl_fix -c scanner039.tif

Reading scanner reflection calibration file and creating "scanner_cal.txt"

[scanner039.tif.zip](https://github.com/doug3236/scanner_refl_fix/files/5504610/scanner039.tif.zip)

Scanner info:
EPSON Expression 1640XL
EPSON Scan Ver. 3.04E

**Comment by doug3236** [comment]
The scanner calibration target must be printed at 100% scale. The scan DPI s/b 200 for best results but it's critical that the chart is printed at 100% as the reflection matrix must be calculated based on the specific dimensions of the various squares. If they are shrunk or enlarged then the matrix will be calculated incorrectly. Also, locating the various squares uses their dimensions to locate them relative to the top/left of the black surround.  However, this should flag an error message rather than just aborting. I'll modify the code to detect this but it will still require that the image is printed at 100% scale.
